# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pydantic-yaml-parser',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/pydantic-yaml-parser',
                'lib_path': 'pydantic_yaml_parser'},
  'syms': { 'pydantic_yaml_parser.yaml': { 'pydantic_yaml_parser.yaml.QuartoDoc': ('yaml.html#quartodoc', 'pydantic_yaml_parser/yaml.py'),
                                           'pydantic_yaml_parser.yaml.Section': ('yaml.html#section', 'pydantic_yaml_parser/yaml.py'),
                                           'pydantic_yaml_parser.yaml.YamlModel': ('yaml.html#yamlmodel', 'pydantic_yaml_parser/yaml.py'),
                                           'pydantic_yaml_parser.yaml.YamlModel.from_dict': ( 'yaml.html#yamlmodel.from_dict',
                                                                                              'pydantic_yaml_parser/yaml.py'),
                                           'pydantic_yaml_parser.yaml._fmt': ('yaml.html#_fmt', 'pydantic_yaml_parser/yaml.py'),
                                           'pydantic_yaml_parser.yaml.yaml2d': ('yaml.html#yaml2d', 'pydantic_yaml_parser/yaml.py')}}}
